
import java.awt.Image;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Admin_home extends javax.swing.JFrame {
File ph,ph1,movie1;
JFileChooser jfc;
   
    public Admin_home(String name) {
          initComponents();
        setSize(630,630);
         ImageIcon ic=new ImageIcon("D:\\adm.jpeg");
            
           Image img = ic.getImage().getScaledInstance(bg.getWidth(),bg.getHeight(),Image.SCALE_SMOOTH);
           ImageIcon ic1 = new ImageIcon(img);
           bg.setIcon(ic1);
        lb.setText("WELCOME  : "+ name);
      loadCategories();
    }
    void loadCategories()
    {
        String ans=myClient.fetchCategories();
        StringTokenizer st=new StringTokenizer (ans,";;");
        int n =st.countTokens();
        for(int i=1;i<=n;i++)
        {
            String name =st.nextToken();
            cb.addItem(name);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        catname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        movie = new javax.swing.JTextField();
        director = new javax.swing.JTextField();
        cast = new javax.swing.JTextField();
        utube_id = new javax.swing.JTextField();
        photo1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Algerian", 3, 60)); // NOI18N
        lb.setForeground(new java.awt.Color(0, 255, 255));
        lb.setText("WELCOME");
        getContentPane().add(lb);
        lb.setBounds(350, 10, 830, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Add Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 80, 240, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Category name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 250, 60);
        getContentPane().add(catname);
        catname.setBounds(320, 150, 150, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 260, 110, 30);
        getContentPane().add(photo);
        photo.setBounds(300, 240, 190, 160);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("Choose Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 430, 270, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 540, 160, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel4.setText("Add movies");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(890, 50, 280, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Select Category");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 132, 300, 48);

        cb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));
        getContentPane().add(cb);
        cb.setBounds(1010, 140, 160, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("movie_name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 220, 280, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("Director");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(720, 290, 250, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("Cast");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 370, 230, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Trailer");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(730, 450, 130, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Photo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(840, 640, 140, 48);

        movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieActionPerformed(evt);
            }
        });
        getContentPane().add(movie);
        movie.setBounds(1010, 220, 210, 50);
        getContentPane().add(director);
        director.setBounds(1010, 300, 210, 50);
        getContentPane().add(cast);
        cast.setBounds(1010, 370, 210, 50);
        getContentPane().add(utube_id);
        utube_id.setBounds(1010, 450, 210, 60);
        getContentPane().add(photo1);
        photo1.setBounds(1020, 600, 230, 160);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1290, 640, 90, 27);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1090, 770, 90, 27);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel11.setText("choose movie");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(730, 530, 230, 40);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("choose movie");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 540, 220, 50);
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1390, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jfc=new JFileChooser();
        int ans =jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
            ph=jfc.getSelectedFile();
            ImageIcon ic =new ImageIcon(ph.getPath());
            Image img =ic.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic1 =new ImageIcon(img);
        photo.setIcon(ic1);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String category = catname.getText();
        
        if(catname.equals("")||ph==null)
        {
            JOptionPane.showMessageDialog(rootPane, "All Fields are Mandatory");
        }
        else
        {
            String ans = myClient.addcat(category,ph);
            System.out.println(ans);
            
            if(ans.equals("success"))
            {
                JOptionPane.showMessageDialog(rootPane, "Added Successfully");
            }
            else if(ans.equals("exist"))
            {
                JOptionPane.showMessageDialog(rootPane, "Category Already Exist");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Failed");
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieActionPerformed

    }//GEN-LAST:event_movieActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jfc=new JFileChooser();
       int ans = jfc.showOpenDialog(this);
       if(ans==JFileChooser.APPROVE_OPTION)
       {
           ph1=jfc.getSelectedFile();
            ImageIcon ic=new ImageIcon(ph1.getPath());
            
            Image img = ic.getImage().getScaledInstance(photo1.getWidth(),photo1.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            photo1.setIcon(ic1);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String category=(String)cb.getSelectedItem();
        String movie_name=movie.getText();
        String direct=director.getText();
        String starcast=cast.getText();
        String youtube=utube_id.getText();
        if(category.equals("")||movie.equals(" ")||direct.equals("")||starcast.equals(" ")||youtube.equals(" ")||ph1.equals(null)||movie1==null)
        {
            JOptionPane.showMessageDialog(rootPane, "all fields are mandatory");
        }
        else
        {
            String ans =myClient.addmovie(category,movie_name,direct,starcast,youtube,ph1,movie1);
            System.out.println("ans is"+ans);
            if(ans.equals("success"))
            {
                 JOptionPane.showMessageDialog(rootPane, "added successfully");
            }
        else
            {
                 JOptionPane.showMessageDialog(rootPane, "failed");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jfc=new JFileChooser();
int ans =jfc.showOpenDialog(this);
if (ans==JFileChooser.APPROVE_OPTION)
{
    movie1=jfc.getSelectedFile();
}
    
    }//GEN-LAST:event_jButton5ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cast;
    private javax.swing.JTextField catname;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField director;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb;
    private javax.swing.JTextField movie;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel photo1;
    private javax.swing.JTextField utube_id;
    // End of variables declaration//GEN-END:variables
}
