

import static java.awt.Color.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rupal
 */
public class Fetch_movies extends javax.swing.JFrame {

   String catname;
    public Fetch_movies(String category)
    {   
        initComponents();
        setSize(1500,2000);
        catname=category;
         lb.setText("WELCOME");
        mainpanel.setBackground(black);
      
       
         
       mainpanel.setAutoscrolls(true);
        loadmovies();
    }
void loadmovies()
{
   String ans = myClient.Fetch_movies(catname);
        System.out.println(ans);
        StringTokenizer st = new StringTokenizer(ans,";;");
      
        int n = st.countTokens();
        
        JButton arr[] = new JButton[n];
        
        int x=10,y=10;
        
        for (int i = 0; i < n; i++) 
        {
            String row = st.nextToken();
            StringTokenizer st1 = new StringTokenizer(row,"$");
           String id=st1.nextToken();
            String name = st1.nextToken();
            String photo = st1.nextToken();
         arr[i]=new JButton(id);
            arr[i] = new JButton(name);
         arr[i].setBounds(x, y, 480, 350);
          ImageIcon ic = new ImageIcon(photo);
          
          Image img = ic.getImage().getScaledInstance(300, 350, Image.SCALE_SMOOTH);
          
          ImageIcon ic1 = new ImageIcon(img);
          
          arr[i].setIcon(ic1);
          arr[i].setFont(new Font("Algerian",Font. BOLD,20));
          arr[i].setBackground(black);
          
          arr[i].addActionListener(new ActionListener() {
            @Override
                     public void actionPerformed(ActionEvent e)
                     {
            JOptionPane.showMessageDialog(rootPane,name+ "Clicked");
                               movie_detail obj =new movie_detail(id);
                               obj.setVisible(true);
                     }
       });
          
        mainpanel.add(arr[i]);
          mainpanel.repaint();
          
        
          if(x<=520)
          {
              x= x+450;
          }
         else
          {
              x=10;
              y=y+360;
          }
        
        
     mainpanel.setPreferredSize(new Dimension(1500, n*400));
    
        }
    

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Brush Script MT", 3, 50)); // NOI18N
        lb.setForeground(new java.awt.Color(204, 0, 102));
        lb.setText("WELCOME");
        getContentPane().add(lb);
        lb.setBounds(230, 10, 1130, 80);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1488, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1468, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 1460, 1320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fetch_movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fetch_movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fetch_movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fetch_movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fetch_movies(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
