
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rupal
 */
public class movie_detail extends javax.swing.JFrame
{

   String movie_id;
    public movie_detail(String id) {
        initComponents();
        setSize(1000,600);
        moviename.setEnabled(false);
         castlb.setEnabled(false);
        movie_id=id;
         ImageIcon ic=new ImageIcon("D:\\moviedetail.jpg");
            Image img = ic.getImage().getScaledInstance(background.getWidth(),background.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            background.setIcon(ic1);
        loadmovie();
    }
void loadmovie()
{
    String ans =myClient.movie_detail(movie_id);
    StringTokenizer st=new StringTokenizer(ans,"$");
    String movie_name=st.nextToken();
    String cast=st.nextToken();
    String youtube_id=st.nextToken();
    String photo=st.nextToken();
    String movie_link=st.nextToken();
    ImageIcon ic = new ImageIcon(photo);
          
          Image img = ic.getImage().getScaledInstance(photolb.getWidth(),photolb.getHeight(),Image.SCALE_SMOOTH);
          
          ImageIcon ic1 = new ImageIcon(img);
          
          photolb.setIcon(ic1);
          moviename.setText(movie_name);
         moviename.setFont(new Font("Algerian",Font. BOLD,20));
      
          castlb.setText(cast);
          castlb.setFont(new Font("Algerian",Font. BOLD,20));
      
          trailerbt.addActionListener(new ActionListener()
                  {
        @Override
        public void actionPerformed(ActionEvent e) {
            try{
                URI uri=new URI("https://www.youtube.com/watch?v="+youtube_id);
                Desktop d = Desktop.getDesktop();
                   
                   d.browse(uri);
               
            }
            catch (Exception ex) 
               {
               }
           
        }
                      
                  }
                  );
            
       button.addActionListener(new ActionListener()
               {
        @Override
        public void actionPerformed(ActionEvent e) 
        {try
        {
           File f=new File(movie_link);
           Desktop d=Desktop.getDesktop();
           d.open(f);
          }
        catch(Exception ex)
               {
                 ex.printStackTrace();
               }
        }
               }                   
               
       );
               
}     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photolb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moviename = new javax.swing.JTextField();
        castlb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        trailerbt = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        photolb.setText("jLabel2");
        getContentPane().add(photolb);
        photolb.setBounds(10, 10, 525, 680);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Movie_name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(549, 38, 133, 39);
        getContentPane().add(moviename);
        moviename.setBounds(549, 95, 380, 38);
        getContentPane().add(castlb);
        castlb.setBounds(557, 222, 460, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Cast  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(557, 160, 206, 50);

        button.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        button.setText("PLAY MOVIE");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button);
        button.setBounds(560, 460, 214, 63);

        trailerbt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        trailerbt.setText("PLAY TRAILER");
        trailerbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailerbtActionPerformed(evt);
            }
        });
        getContentPane().add(trailerbt);
        trailerbt.setBounds(560, 310, 210, 70);
        getContentPane().add(background);
        background.setBounds(547, 6, 640, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

    }//GEN-LAST:event_buttonActionPerformed

    private void trailerbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailerbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trailerbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_detail("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton button;
    private javax.swing.JTextField castlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField moviename;
    private javax.swing.JLabel photolb;
    private javax.swing.JButton trailerbt;
    // End of variables declaration//GEN-END:variables

    
}