
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rupal
 */
public class SERVERON_OFF extends javax.swing.JFrame {

    
     my_server obj;
    public SERVERON_OFF() {
        initComponents();
          setSize(500, 500);
           ImageIcon ic=new ImageIcon("D:\\server.jpg");
            
            Image img = ic.getImage().getScaledInstance(background.getWidth(),background.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            background.setIcon(ic1);
            
             ImageIcon ic2=new ImageIcon("D:\\vod2.jpg");
            Image img1 = ic2.getImage().getScaledInstance(bg.getWidth(),bg.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon ic3 = new ImageIcon(img1);
            bg.setIcon(ic3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startbt = new javax.swing.JButton();
        stopbt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        startbt.setFont(new java.awt.Font("Arial Black", 3, 80)); // NOI18N
        startbt.setText("Start Server");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });
        getContentPane().add(startbt);
        startbt.setBounds(40, 90, 600, 100);

        stopbt.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 80)); // NOI18N
        stopbt.setText("Stop Server");
        stopbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtActionPerformed(evt);
            }
        });
        getContentPane().add(stopbt);
        stopbt.setBounds(50, 350, 590, 100);

        jButton1.setFont(new java.awt.Font("Engravers MT", 3, 55)); // NOI18N
        jButton1.setText("LAUNCH MY VOD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 260, 670, 80);
        getContentPane().add(background);
        background.setBounds(10, 0, 680, 710);
        getContentPane().add(bg);
        bg.setBounds(690, 6, 770, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
         try {
            obj = new my_server(9000);
            startbt.setEnabled(false);
            stopbt.setEnabled(true);
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_startbtActionPerformed

    private void stopbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtActionPerformed
         obj.shutdown();
       startbt.setEnabled(true);
       stopbt.setEnabled(false);
    }//GEN-LAST:event_stopbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Welcome obj=new Welcome();
       obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SERVERON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SERVERON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SERVERON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SERVERON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SERVERON_OFF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton startbt;
    private javax.swing.JButton stopbt;
    // End of variables declaration//GEN-END:variables
}
