
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rupal
 */
public class user_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home
     */
    public user_home(String email)
    {
        initComponents();
        setSize(1000,1000);
        lb.setText("WELCOME  : "+ email);
        
             mainpanel.setAutoscrolls(true);
             mainpanel.setBackground(Color.red);
            loadcategory();
    }
void loadcategory()
{
    String ans=myClient.fetchcat();
    System.out.println(ans);
    StringTokenizer st =new StringTokenizer(ans,";;");
    int n=st.countTokens();
    JButton arr[]=new JButton[n];
    int x=5,y=5,count=1;
    for(int i =0;i<n;i++)
    {
        String row = st.nextToken();
         StringTokenizer st1=new StringTokenizer(row,"$");
         String name =st1.nextToken();
         String photo=st1.nextToken();
         arr[i]=new JButton(name);
         ImageIcon ic=new ImageIcon(photo);
            
            Image img = ic.getImage().getScaledInstance(250,250,Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
         arr[i].setIcon(ic1);
         arr[i].setFont(new Font("Algerian",Font. BOLD,20));
      
         arr[i].setBounds(x, y,10, 10);
        arr[i].addActionListener(new ActionListener() {
            @Override
                     public void actionPerformed(ActionEvent e)
                     {
            JOptionPane.showMessageDialog(rootPane,name+ "Clicked");
                               Fetch_movies obj =new Fetch_movies(name);
                               obj.setVisible(true);
                     }
       });
         mainpanel.add(arr[i]);
         mainpanel.repaint();
         if(x<=30)
         {
         x=x+10;
         }
         else
         {
             count=count+1;
             x=1;
             y=y+10;
         }
        
    
    mainpanel.setPreferredSize(new Dimension(500,n*100));
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
}
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(null);

        lb.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 51, 51));
        lb.setText("WELCOME");
        getContentPane().add(lb);
        lb.setBounds(180, 0, 910, 60);

        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 1420, 640);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT CATEGORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 80, 660, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
